services:
  api:
    build:
      context: ..
      dockerfile: ./deploy/Dockerfile
    environment:
      DATABASE_URL: postgres://mydbuser:mydbpwd@db:5432/mydbname?sslmode=disable
      API_PORT: 80
    ports:
      - "80:80"
    depends_on:
      db:
        condition: service_healthy
        restart: true
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: mydbname
      POSTGRES_USER: mydbuser
      POSTGRES_PASSWORD: mydbpwd
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q -U mydbuser -d mydbname"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - ./.compose-data/pgdata:/var/lib/postgresql/data
  migrate:
    image: migrate/migrate
    volumes:
      - ../db/migrations:/migrations
    command: [ "-path", "/migrations", "-database",  "postgres://mydbuser:mydbpwd@db:5432/mydbname?sslmode=disable", "up" ]
    depends_on:
      db:
        condition: service_healthy
        restart: true